[platformio]
default_envs = m5stack-atom
src_dir = tests/test_01_atom_relay_button/src

[env:m5stack-atom]
platform = espressif32@6.7.0
board = m5stack-atom
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-515A44874B
upload_port = /dev/cu.usbserial-515A44874B
lib_deps =
  fastled/FastLED@^3.10.3
